# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build-base:
    runs-on: ubuntu-latest
    name: Update NuGet package for Culture Models
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/Ho-Ly-Games/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution and generate NuGet package
        run: |
          cd LcboStatsApi
          dotnet build --configuration Release

      - name: Push generated package to GitHub registry
        run: dotnet nuget push "LcboStatsApi/bin/Release/LcboStatsApi.*.nupkg" --skip-duplicate --no-symbols